#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

clone:
  depth: full

definitions:
  steps:
    - step: &staging
        name: Deploy to Heroku
        deployment: staging
        caches: 
          - pip
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
    - step: &production
        name: Deploy to Heroku
        deployment: production
        caches: 
          - pip
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
          
pipelines:
  branches:
    develop:
      - step: *staging
    master:
      - step: *production